services:
  postgres:
    image: postgres:16-alpine
    container_name: cicd-postgres
    environment:
      POSTGRES_DB: cicd
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

  test:
    image: maven:3.9.6-eclipse-temurin-21
    volumes:
      - ./Backend:/app
      - maven-repo:/root/.m2/repository
    working_dir: /app
    depends_on:
      - postgres
    command: bash -c "sleep 30 && mvn test"
    networks:
      - app-network

volumes:
  postgres_data:
  maven-repo:

networks:
  app-network:
    driver: bridge
