spring:
  datasource: # Configuración de la fuente de datos.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cicd} 
    username: ${SPRING_DATASOURCE_USERNAME:user} # Usuario de la Base de Datos.
    password: ${SPRING_DATASOURCE_PASSWORD:pass} # Contraseña del usuario.
    driver-class-name: org.postgresql.Driver

  jpa: # Configuración de JPA
    hibernate: # Configuración específica de Hibernate
      ddl-auto: create-drop # BORRA y RECREA tablas cada inicio
    show-sql: true # Muestra SQL en consola
server:
  port: 8080